// src/qwik/useElementSize.ts
import { type Signal, useSignal, useVisibleTask$ } from "@builder.io/qwik";
import { type ContainerSize, getContainerSize, observeContainer } from "../core/container.js";

export type UseElementSizeResult = { width: number; height: number };

const DEFAULT_SIZE: UseElementSizeResult = { width: 0, height: 0 };

export function useElementSize(
  ref: { current: Element | null },
  serverDefault: UseElementSizeResult = DEFAULT_SIZE,
  options: { debounce?: number; throttle?: number } = {},
): Signal<UseElementSizeResult> {
  const size = useSignal<UseElementSizeResult>(serverDefault);

  useVisibleTask$(({ cleanup }) => {
    const el = ref.current;
    if (!el) return;
    size.value = getContainerSize(el);
    const unsub = observeContainer(
      el,
      (s: ContainerSize) => { size.value = { width: s.width, height: s.height }; },
      options,
    );
    cleanup(unsub);
  });

  return size;
}

// src/react/useElementSize.ts
"use client";

import { type RefObject, useEffect, useState } from "react";
import { type ContainerSize, getContainerSize, observeContainer } from "../core/container.js";

export type UseElementSizeResult = { width: number; height: number };

const DEFAULT_SIZE: UseElementSizeResult = { width: 0, height: 0 };

export function useElementSize(
  ref: RefObject<Element | null>,
  serverDefault: UseElementSizeResult = DEFAULT_SIZE,
  options: { debounce?: number; throttle?: number } = {},
): UseElementSizeResult {
  const [size, setSize] = useState<UseElementSizeResult>(serverDefault);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    setSize(getContainerSize(el));
    const unsub = observeContainer(
      el,
      (s: ContainerSize) => setSize({ width: s.width, height: s.height }),
      options,
    );
    return unsub;
  }, [ref, options]);

  return size;
}
